// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
		
		public class MeshGenerator : MonoBehaviour
		{
			public Transform mesh;
			public int nFaces;
			public void Start()
			{
				for (int i = 0; i < nFaces; i += 200) {
					Transform newmesh = Instantiate(mesh, new Vector3(0f, (float)i, 0f), Quaternion.identity) as Transform;
				}
			}
		}
}

