// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//using System;
using UnityEngine;

namespace AssemblyCSharp
{
		
		public class MeshGenerator : MonoBehaviour
		{
			public Transform mesh;
			public int nFaces;
			public void Start()
			{
				for (int i = 0; i < nFaces; i += 200) {
					Vector3 randpos = new Vector3(Random.Range(-5f, 5f), Random.Range(1f, 2f), Random.Range(-5f, 7f));
					Transform newmesh = Instantiate(mesh, randpos, Quaternion.Euler(new Vector3(270, 0, 0))) as Transform;
				}
			}
		}
}

